export const CHANGE_PASSWORD_REQUEST = 'settings/CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'settings/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'settings/CHANGE_PASSWORD_FAILURE';
