export const FETCH_REPORTS_REQUEST = 'FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE';

export const FETCH_REPORT_REQUEST = 'FETCH_REPORT_REQUEST';
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const FETCH_REPORT_FAILURE = 'FETCH_REPORT_FAILURE';

export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAILURE = 'CREATE_REPORT_FAILURE';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAILURE = 'DELETE_REPORT_FAILURE';

export const FETCH_REPORTS_STATS_REQUEST = 'FETCH_REPORTS_STATS_REQUEST';
export const FETCH_REPORTS_STATS_SUCCESS = 'FETCH_REPORTS_STATS_SUCCESS';
export const FETCH_REPORTS_STATS_FAILURE = 'FETCH_REPORTS_STATS_FAILURE';

export const SET_SELECTED_INCIDENT = 'SET_SELECTED_INCIDENT';
export const CLEAR_SELECTED_INCIDENT = 'CLEAR_SELECTED_INCIDENT';
