// Action type constants for Students module
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE';

export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAILURE';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const FETCH_STUDENT_ASSIGNMENTS_REQUEST = 'FETCH_STUDENT_ASSIGNMENTS_REQUEST';
export const FETCH_STUDENT_ASSIGNMENTS_SUCCESS = 'FETCH_STUDENT_ASSIGNMENTS_SUCCESS';
export const FETCH_STUDENT_ASSIGNMENTS_FAILURE = 'FETCH_STUDENT_ASSIGNMENTS_FAILURE';

export const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';
export const CLEAR_SELECTED_STUDENT = 'CLEAR_SELECTED_STUDENT';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const IMPORT_STUDENTS_REQUEST = 'IMPORT_STUDENTS_REQUEST';
export const IMPORT_STUDENTS_SUCCESS = 'IMPORT_STUDENTS_SUCCESS';
export const IMPORT_STUDENTS_FAILURE = 'IMPORT_STUDENTS_FAILURE';
export const IMPORT_EXAMS_REQUEST = 'IMPORT_EXAMS_REQUEST';
export const IMPORT_EXAMS_SUCCESS = 'IMPORT_EXAMS_SUCCESS';
export const IMPORT_EXAMS_FAILURE = 'IMPORT_EXAMS_FAILURE';
